#!/usr/bin/env bash
#Transfers to file
if [ $# -lt 4 ]
then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
# Define the source and destination files
# SOURCE_FILE=$1
# DESTINATION_FILE="~/"
# User =$2
# SSH_FILE$3
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
# Transfer thie file using SCP
# scp $SOURCE_FILE $DESTINATION_FILE
