#!/usr/bin/env bash
sudo apt update -y
sudo apt install nginx -y
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "<html><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo killall -s QUIT nginx
sudo killall -s HUP nginx
# Restart Nginx
sudo nginx
