#!/usr/bin/env bash
# this is installing

sudo su
apt -y update 
apt-get -y install nginx
#sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
#service nginx restart
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
#echo "Hello World!" | sudo tee /var/www/html/index.html
#chown www-data:www-data /var/www/html/index.html
#chmod 644 /var/www/html/index.html
service nginx start
