#!/usr/bin/env bash
# Rediraction
#sudo su
#apt -y update
#apt-get -y install nginx
#ufw allow 'Nginx HTTP'     
#echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html      
#service nginx start
./1-install_nginx_web_server
DEST="/etc/nginx"
url="https://www.youtube.com/watch?v=QH2-TGUlwu4"
LINE="location /redirect_me {\nreturn 301 $url;\n}"
sudo sed -i "\$i $LINE" $DEST/sites-available/default
sudo service nginx restart
