#!/usr/bin/env bash
# Rediraction
sudo apt update
sudo apt -y install nginx
DEST="/etc/nginx/sites-available/default"
url="https://www.youtube.com/watch?v=QH2-TGUlwu4"
# Create the new location block
NEW_LOCATION="location /redirect_me {"
NEW_LOCATION+="\nreturn 301 $url;"
NEW_LOCATION+="\n}"
# Use sed to replace the existing location block with the new one
#sudo sed -i '/location \/ {/,/}/d' $DEST
#sudo sed -i "\$i $NEW_LOCATION" $DEST
sudo sed -i '/location \/ {/,/}/d' $DEST
sudo sed -i "/server {/a $NEW_LOCATION" $DEST
sudo service nginx restart
