#!/usr/bin/env bash
# Not found page 404
sudo ./3-redirection
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /usr/share/nginx/html

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
# Create the custom 404 page
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
#Appending the error config after the above new_string.
error_config_string="\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\n$error_config_string/" /etc/nginx/sites-available/default
sudo chown -R root:root /var/www/html
sudo chown -R root:root /usr/share/nginx/html
sudo service nginx restart
