#!/usr/bin/env bash
# configure web-02 to be identical to web-01.
sudo service nginx restart
sudo apt-get update
cat <<EOF > /etc/nginx/conf.d/custom_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By $hostname;
        root /var/www/html;
        index index.html index.htm;
    }
}
EOF
sudo service nginx restart
