#!/usr/bin/env bash
# installing HAproxy
sudo apt-get -y update
sudo apt-get install -y haproxy
# Configure HAproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo sed -i '/^frontend.*$/,$d' /etc/haproxy/haproxy.cfg
# Add frontend configuration
echo "
frontend http-in
    bind *:80
    mode http
    default_backend servers

backend servers
    balance roundrobin
    server 422351-web-01 100.25.160.172:80 check
    server 422351-web-02 34.203.38.176:80 check

" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy start
