#!/usr/bin/env bash
# installing HAproxy
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" > sudo /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 422351-web-01 100.25.160.172:80 check
   server 422351-web-02 34.203.38.176:80 check
" >> sudo /etc/haproxy/haproxy.cfg

sudo service haproxy start
