#!/usr/bin/env bash
# Using what you did for task #0 to make it short.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
