#!/usr/bin/env bash
#Print "Best School" 10 times w/ while loop and then , say bad luck on 4th turn,
#good luck on 7th

i="0"
while ((i < 10)); do
    if [ $i == 3 ]; then
	echo "bad luck"

    elif [ $i == 7 ]; then
	echo "good luck"
    else
        echo "Best School"
    fi

    i=$((i + 1))
done
