#!/usr/bin/env bash
# script to  install the ufw firewall and setup a few rules on web-01.
apt-get update
apt-get install -y ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp 
echo "y" | ufw enable

