#!/usr/bin/env bash
# change hosts asignments
NEW="8.8.8.8 facebook.com"

cp /etc/hosts host.new
sed -i -E "s/127.0.0.1/127.0.0.2/" host.new
sed -i "$ a $NEW" host.new
cp -f host.new /etc/hosts
rm host.new
